---
- name: "Check if distro or architecture is supported"
  ansible.builtin.set_fact:
    distro_supported: "{{ (supported_distros | selectattr('name', 'equalto', ansible_distribution) | list | length > 0) and
                         (ansible_distribution_version is version(supported_distros | selectattr('name', 'equalto', ansible_distribution) | map(attribute='min_version') | first, '>=')) and
                         (ansible_architecture in (supported_distros | selectattr('name', 'equalto', ansible_distribution) | map(attribute='supported_architectures', default=[]) | first)) }}"

- name: "Display if distro or architecture is not supported"
  ansible.builtin.debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} on {{ ansible_architecture }} is not supported"
  when: distro_supported is false

# For molecule testing only
- name: "Create file if distro is not supported"
  ansible.builtin.copy:
    dest: "/tmp/unsupported_distro"
    content: "unsupported"
    mode: "0644"
  no_log: true
  when: distro_supported is false and "molecule-notest" in ansible_skip_tags
