---
- name: "Ensure Python 3 is installed"
  ansible.builtin.apt:
    name: "python3"
    state: "present"

- name: "Set URL architecture"
  ansible.builtin.set_fact:
    url_architecture: "{{ ('amd64' if ansible_architecture == 'x86_64' else 'arm64' if ansible_architecture == 'aarch64' else 'unknown') | string | trim }}"

- name: "Ensure ssm-agent is installed (apt)"
  ansible.builtin.apt:
    deb: "https://s3.{{ ansible_ec2_placement_region }}.amazonaws.com/amazon-ssm-{{ ansible_ec2_placement_region }}/latest/debian_{{ url_architecture }}/amazon-ssm-agent.deb"
    state: present
    update_cache: true
    cache_valid_time: 3600
  notify:
    - "Enable amazon-ssm-agent"

- name: "Flush handlers"
  ansible.builtin.meta: flush_handlers


