---
# tasks file for installing software on Ubuntu using snaps

- name: "Ensure snapd is installed"
  ansible.builtin.apt:
    name: snapd
    update_cache: true
    cache_valid_time: 3600
    state: present

- name: "Ensure snapd service is started and enabled"
  ansible.builtin.systemd:
    name: snapd
    state: started
    enabled: true

- name: "Ensure amazon-ssm-agent is installed (snap)"
  community.general.snap:
    name: amazon-ssm-agent
    state: present
    classic: true
  notify: "Enable amazon-ssm-agent snap"
