---
# tasks file for netdata

- name: "Gathering facts"
  become: true
  ansible.builtin.setup:
  when: ansible_facts|default({}) == {}

# - name: "Assert"
#   ansible.builtin.import_tasks: assert.yml
#   run_once: true
#   delegate_to: localhost

- name: "Distro Requirements"
  ansible.builtin.include_tasks: distro-requirements.yml

- name: "Become block"
  become: true
  block:
    - name: "Install"
      ansible.builtin.include_tasks: install-Debian.yml
      when: ansible_os_family == "Debian"

    - name: "Install"
      ansible.builtin.include_tasks: install-RedHat.yml
      when: ansible_os_family == "RedHat"
