---
# tasks file for amazon_ssm_agent

- name: "Gathering facts"
  ansible.builtin.setup:
  when: ansible_facts|default({}) == {}

- name: "Gather package facts"
  ansible.builtin.package_facts:

- name: "Distro Requirements"
  ansible.builtin.include_tasks: distro-requirements.yml

- name: "Become block"
  become: true
  block:
    - name: "Remove"
      ansible.builtin.include_tasks: remove.yml
      when: amazon_ssm_agent_state == "absent"

    - name: "Install (Ubuntu)"
      ansible.builtin.include_tasks: install-Ubuntu.yml
      when: ansible_distribution == "Ubuntu" and amazon_ssm_agent_state == "present" and ('amazon-ssm-agent' not in ansible_facts.packages or amazon_ssm_agent_force_install)

    - name: "Install (Debian Family)"
      ansible.builtin.include_tasks: install-Debian.yml
      when: ansible_os_family == "Debian" and ansible_distribution != "Ubuntu" and amazon_ssm_agent_state == "present" and ('amazon-ssm-agent' not in ansible_facts.packages or amazon_ssm_agent_force_install)

    - name: "Install (RedHat Family)"
      ansible.builtin.include_tasks: install-RedHat.yml
      when: ansible_os_family == "RedHat" and amazon_ssm_agent_state == "present" and ('amazon-ssm-agent' not in ansible_facts.packages or amazon_ssm_agent_force_install)
