---
# tasks file for netdata

- name: "Pre-task: Check if role should run"
  hosts: all
  tasks:
    - name: "Gathering facts"
      ansible.builtin.setup:
      when: ansible_facts|default({}) == {}


- name: "Distro Requirements"
  ansible.builtin.include_tasks: distro-requirements.yml

- name: "Become block"
  become: true
  block:
    - name: "Install  (Ubuntu)"
      ansible.builtin.include_tasks: install-Ubuntu.yml
      when: ansible_distribution == "Ubuntu"

    - name: "Install (Debian Family)"
      ansible.builtin.include_tasks: install-Debian.yml
      when: ansible_os_family == "Debian" and ansible_distribution != "Ubuntu"

    - name: "Install (RedHat Family)"
      ansible.builtin.include_tasks: install-RedHat.yml
      when: ansible_os_family == "RedHat"
